### ISSUE TITLE
SqlAdapter installation failed 

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/AZ-600-Configuring-and-Operating-Microsoft-Azure-Stack-Hub#10]
# Module: 02
#### Step: 09

Description of issue
Lab :  Implement SQL Server Resource Provider in Azure Stack Hub
While trying to install the SQL Server resource Provider, after executing the Step # 9 in the windows PowerShell, its throwing an error SqlAdapter installation failed.

![M2_L4_ImplementSQL_SQLAdapterfailed](https://user-images.githubusercontent.com/92770552/154752474-6d7b4082-f757-4a53-949a-a4d08709b5ee.png)

![logfile1](https://user-images.githubusercontent.com/92770552/154753401-39c2dda5-9647-4a2e-8734-2a077fb40fb9.png)

![logfile2](https://user-images.githubusercontent.com/92770552/154753427-a3156ec4-89fa-4ecb-8246-579b2b021ae1.png)

Repro steps:

1. Module 2 >> Lab : Implement SQL server resource provider in Azure Stack Hub >> Exercise 1 >> Task 2 >> Step#9.

Instruction is to change the current directory to the location of the extracted SQL Server resource provider installation files.  

As per the instruction downloaded the SQL Resource Provider self-extracting executable from (https://aka.ms/azshsqlrp11931) and extracted its content into the C:\Downloads\SQLRP folder.

**Comment by polichtm** [comment]
under investigation
rgds
Marcin

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review Confirms this issue.

**Comment by polichtm** [comment]
This has been resolved. Pls let us know if you experience any other issues with this lab
rgds
Marcin
