### ISSUE TITLE
Unable to build cloud capabilities in Lab 03 of Module 02

### ISSUE THREAD

**Issue by mahendra-shinde** [MicrosoftLearning/AZ-600-Configuring-and-Operating-Microsoft-Azure-Stack-Hub#29]
# Module: 02
#### Step: 13

Get-AzCloudCapability returns Error 400 (Bad request). Not able to build the capabilities file.

Repro steps:

1. Follow all the steps in Task 1 or Exercise 1 till the step 12 
1. Get-AzCloudCapability -Location 'local' -OutputPath $path\AzureCloudCapabilities.Json -Verbose
![screen](https://user-images.githubusercontent.com/17270401/189480469-50637d1e-8fd6-404d-8133-f68fdb5a4602.png)

**Comment by polichtm** [comment]
Hi Mahendra,
to confirm, are you running this from an ASDK host?
rgds
Marcin

**Comment by mahendra-shinde** [comment]
Hi, I am using it from the labs we MCTs use.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by polichtm** [comment]
Hi Mahendra,
which lab environment/platform in particular are you referring to? 
Here is what I'm seeing when running this on the Xtreme lab platform:
![image](https://user-images.githubusercontent.com/10284906/192149052-52b1360a-7f20-4f17-b079-fc616c1a9985.png)
What's the version of ASDK you are using?
rgds
Marcin

**Comment by polichtm** [comment]
switching to #30 due to lack of response
