### ISSUE TITLE
LAB_0201_Manage_Offers_and_Plans | Lab Environment

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-600-Configuring-and-Operating-Microsoft-Azure-Stack-Hub#3]
# Module: 0201
Lab Environment

Description of issue: It would be better to provide a pointer at the beggining of this lab under "Lab Envronment" which explains ASDK and how to deploy it for AZ-600 labs. It doesnt say anything about ASDK at the moment so I had to google for it.

The pointer can be "https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-what-is?view=azs-2102".

Thanks

**Comment by polichtm** [comment]
Hi Azhar,
this topic is covered in the course. Pls reach out to your instructor regarding any questions you might need regarding ASDK
rgds
Marcin
