### ISSUE TITLE
Not able to generate Cloud Capabilities JSON file

### ISSUE THREAD

**Issue by harshita3199** [MicrosoftLearning/AZ-600-Configuring-and-Operating-Microsoft-Azure-Stack-Hub#30]
# Module: 02
#### Step: 13

Description of issue
I am running these cmdlet in Powershell 7 as an administrator

Image attached
![image](https://user-images.githubusercontent.com/39816522/194512582-22dcc06e-fe81-4873-bae1-d8b700d0636c.png)

How to resolve this?

**Comment by polichtm** [comment]
Hi Mahendra,
which lab environment/platform in particular are you referring to?
Here is what I'm seeing when running this on the Xtreme lab platform:
![image](https://user-images.githubusercontent.com/10284906/194567052-2e444094-b9da-44f9-b275-cfaa5d0d3acb.png)

What's the version of ASDK you are using?
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
