### ISSUE TITLE
Unable to access the MySQL Server 5.6 on Ubuntu VM page in Module 2

### ISSUE THREAD

**Issue by junnhssn** [MicrosoftLearning/AZ-600-Configuring-and-Operating-Microsoft-Azure-Stack-Hub#4]
# Module: 2: Provide Services
#### Step: 1,3 and 4

Description of issue
Unable to access the [ MySQL Server 5.6 on Ubuntu VM page](https://github.com/Azure/azure-quickstart-templates/tree/master/mysql-standalone-server-ubuntu) in steps 1,3 and 4. Therefore, unable to proceed further. Please advise.

![image](https://user-images.githubusercontent.com/47213023/139065092-8238d67a-9b9f-489e-a82b-752b1167c388.png)

![image](https://user-images.githubusercontent.com/47213023/139065846-39aae177-2c5f-4e6a-b767-410db6776d6b.png)

**Comment by polichtm** [comment]
updated
