### ISSUE TITLE
LAB_0201_Manage_Offers_and_Plans - 2nd user account login intended?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-600-Configuring-and-Operating-Microsoft-Azure-Stack-Hub#5]
# Module: 02
## Lab/Demo: Manage offers and plans in Azure Stack Hub
Exercise 4
#### Step: 02

Description of issue
Instruct reads:
1. In the web browser window, navigate to the [Azure Stack Hub user portal](https://portal.local.azurestack.external) and sign in as **t1u1@azurestack.local** with the password **Pa55w.rd**.

However, this section is subtitled "_(as the second user)_" so I believe this should actually read:

1. In the web browser window, navigate to the [Azure Stack Hub user portal](https://portal.local.azurestack.external) and sign in as **t1u2@azurestack.local** with the password **Pa55w.rd**.

**Comment by polichtm** [comment]
updated
rgds
Marcin
